### ISSUE TITLE
安卓手机上好像有点卡卡的

### ISSUE THREAD

**Issue by towelong** [ChatBot-All/chatbot-app#10]

**Comment by jiang111** [comment]
是慢，还是掉帧的卡，因为 UI 逻辑全部采用的是 iOS 风格，所以整体动画会比较慢,如果是掉帧的卡，可以录个小视频看一下

**Comment by towelong** [comment]
> 是慢，还是掉帧的卡，因为 UI 逻辑全部采用的是 iOS 风格，所以整体动画会比较慢,如果是掉帧的卡，可以录个小视频看一下

应该是UI的关系，不是掉帧
