### ISSUE TITLE
未来会支持poe的api吗？

### ISSUE THREAD

**Issue by DonChen916** [ChatBot-All/chatbot-app#11]
POE订阅支持使用ChatGPT4.0和Claude opus，未来有机会支持添加poe的api吗？

**Comment by DonChen916** [comment]
https://poe.com/api_key  这个地址可以申请poe ai的api

**Comment by jiang111** [comment]
这个 api_key 好像只是用来创建和使用特定的 bot 的吧，不像其他平台的 key 可以全局调用
