### ISSUE TITLE
你好，支持deepseek的api吗？

### ISSUE THREAD

**Issue by huzhizhao** [ChatBot-All/chatbot-app#12]
**APP Version/Mobile Platform**
App最新版本  设备为iPhone IOS 14.2.1
**Content**
deepseek的API支持吗？在PC设备上的Chatbox可以正常使用的。希望能支持
**Screenshot**
![f395181b8c010edfcc04ec5bd70817a](https://github.com/ChatBot-All/chatbot-app/assets/24367129/21d63446-43b6-4424-8178-36f18e9a3f0e)

**Comment by jiang111** [comment]
支持的![image](https://github.com/ChatBot-All/chatbot-app/assets/3346368/4aea03a2-3e2e-48d2-b094-2dfc3d0f5dee)

**Comment by huzhizhao** [comment]
奇怪，为啥我的会显示不出来内容呢？

**Comment by jiang111** [comment]
临时生成一个新的 key 试一下，如果还是不行，把 key 发到 newtab12138@gmail.com ，我来调试一下

**Comment by huzhizhao** [comment]
是新的Key来的
已重新创建一个Key发送到上面的邮箱，请注意查收
