### ISSUE TITLE
增加自定义模型功能

### ISSUE THREAD

**Issue by hscmcc1** [ChatBot-All/chatbot-app#13]
大佬，对于获取模型列表失败的key，是否可以增加自定义模型功能，因为默认模型不完整。

**Comment by jiang111** [comment]
可以的

**Comment by hscmcc1** [comment]
另外，是否可以在会话中增加一个清除上下文的按钮？当前要清除上下文只能重开一个会话。

**Comment by jiang111** [comment]
> 另外，是否可以在会话中增加一个清除上下文的按钮？当前要清除上下文只能重开一个会话。

可以，置顶的随便聊聊里也是不携带上下文的

**Comment by hscmcc1** [comment]
置顶的随便聊聊虽然不包含上下文，但每次会话刚问几个问题就需要新开窗口，否则上下文很长，这样不利于查找问题，最好是一个会话可以很长，又可以随时清除上下文，不至于消耗太多token。

**Comment by hscmcc1** [comment]
大佬，现在上下文可以清除了，但内容也没了，有时还需要保留记录，是否可以只清除上下文，而不清除内容？类似于打开随便聊聊的效果，但随便聊聊每次都是同一个窗口，时间长了内容不好查找，我想不同类型的问题在不同的窗口提问，然后点击清除上下文后，文字内容还在，只是token可以重新计算，不包含前面的内容，可以实现吗？

**Comment by jiang111** [comment]
这个建议直接开新页面，因为开新页面也不消耗 token
