### ISSUE TITLE
自定义模型

### ISSUE THREAD

**Issue by DJ133104** [ChatBot-All/chatbot-app#15]
希望可以自定义模型名称，有些是基于openai类型的接口，但模型名称是其他的，希望可以自定义

**Comment by mao13820** [comment]
您好，非常感谢您的这个项目。我想请问，增加自定义模型的功能目前上线了吗，如何设置？还是说未来会支持，谢谢了

**Comment by jiang111** [comment]
上线了，可以在服务商列表左滑，会出现新增模型按钮

**Comment by mao13820** [comment]
好的，已找到，十分感谢！

**Comment by KiriKira** [comment]
> 上线了，可以在服务商列表左滑，会出现新增模型按钮

这个左滑功能是又删掉了吗。。？现在左滑没有任何反应，想添加自定义模型无法添加
