### ISSUE TITLE
安卓客户端提示更新版本，但是没有最新版本，点击过去是apple store的网址

### ISSUE THREAD

**Issue by suimenqx** [ChatBot-All/chatbot-app#16]
**APP Version/Mobile Platform**
1.2.8版本，安卓

**Content**
suimenqx@gmail.com

**Screenshot**
提示更新
![Screenshot_20240616_162206_com gbox android](https://github.com/ChatBot-All/chatbot-app/assets/30758433/282682ba-b6b6-4fbf-bb7f-0cb6db1a7fdc)
跳转
![Screenshot_20240616_162213_com gbox android](https://github.com/ChatBot-All/chatbot-app/assets/30758433/fb4bbe0c-5dd4-4127-83db-ace555217055)

**Comment by jiang111** [comment]
已修复，新版本 1.3.0
