### ISSUE TITLE
添加模型，使用优化

### ISSUE THREAD

**Issue by DJ133104** [ChatBot-All/chatbot-app#18]
1、希望默认的模型配置可以更新一下，还有添加模型的话，希望可以像这样模型1,模型2这种，用逗号隔开，不然只能一个一个加模型。有望支持像suno音乐生成，还有mj画图那些模型嘛
2、还有API的URL添加后不能修改了，只能重新添加一个，然后再删除旧的那一个，希望可以直接编辑。
3、对一个服务添加完模型后，加入不小心模型添加错了，就不能删除那个错的模型了，好像只能新增，不能删减。（或许我没发现？）

**Comment by jiang111** [comment]
1. 关于自定义模型， 在开发的时候我的本意是尽可能少的让用户手动添加模型，而是通过模型的API自动获取支持的模型列表，所以手动添加模型应该是很少需要操作的。

2 和 3 的需求可以在以后的版本中迭代

**Comment by DJ133104** [comment]
okok，那以后会增加其他绘画模型的支持吗，比如flux还有mj的

**Comment by jiang111** [comment]
如果他们有API的话，后续会慢慢增加

**Comment by jiang111** [comment]
新版本已优化 https://github.com/ChatBot-All/chatbot-app/releases/tag/1.4.1
