### ISSUE TITLE
清空聊天记录的时候会重置标题，即使设置了不自动选取标题

### ISSUE THREAD

**Issue by mao13820** [ChatBot-All/chatbot-app#19]
在使用时，如果开了好几个对话，每个对话设置一个模型，并设置好了标题进行区分，并关闭了自动取标题功能。

此时如果想清空一个对话，不想保留历史记录，会把设置好的对话标题也重置。

不知道我的使用方法是否正确，这样的目的是随时切换不同的模型，而不需要每次进去重新选。但是由于软件特性，每次会重置标题就导致使用不是很方便。

谢谢

**Comment by jiang111** [comment]
是的，清空聊天记录是会重置标题，如果不想重置标题，可以清空上下文。清空上下文之后就不会携带历史聊天记录到服务器

**Comment by jiang111** [comment]
新版本已优化 https://github.com/ChatBot-All/chatbot-app/releases/tag/1.4.1
