### ISSUE TITLE
prompt库

### ISSUE THREAD

**Issue by jingdizhilh** [ChatBot-All/chatbot-app#2]
建议增加 创建个人的prompt库?

**Comment by jingdizhilh** [comment]
生成图片不能发送。。。

**Comment by jiang111** [comment]
prompt在计划中，生成图片需要gpt支持 dall-e-3 ，如果你的api key支持，可以试试其他的app能不能生成，如果可以，再在下面回复

**Comment by jiang111** [comment]
好的，下个版本修复
