### ISSUE TITLE
[Suggestion] 移动"清除上下文"按钮到底部输入框右侧(做成一个图标形式)

### ISSUE THREAD

**Issue by HexWeaverNova** [ChatBot-All/chatbot-app#24]
这样每次都无需点击右上角, 少一层菜单

**Comment by jiang111** [comment]
置顶的随便聊聊不会携带任何上下文。

对于已经有聊天记录了，想发起新的聊天，建议直接点列表右上角新增一条消息，如果不开启自动生成标题，那就没有任何损耗。

手机端不推荐一直通过清除上下文的方式进行对话。
