### ISSUE TITLE
开发者您好！麻烦您打包的无签名的ios ipa安装包，我们会自行签名或者巨魔安装，谢谢你

### ISSUE THREAD

**Issue by ggllqzy** [ChatBot-All/chatbot-app#3]
开发者您好！麻烦您打包的无签名的ios ipa安装包，我们会自行签名或者巨魔安装，谢谢你

**Comment by jiang111** [comment]
已经提交tf了，如果审核能过就发邀请链接，过不了再打包ipa吧

**Comment by jiang111** [comment]
iOS TestFlight已经审核通过了，查看README下载
