### ISSUE TITLE
请求适配

### ISSUE THREAD

**Issue by Jonnyan404** [ChatBot-All/chatbot-app#4]
注册链接: https://burn.hair/register?aff=LjKf

对方的api文档如下:

https://github.com/BurnHair/issues/blob/master/doc.md

**Comment by rouse0031** [comment]
![image](https://github.com/ChatBot-All/chatbot-app/assets/168355390/551f4f37-2153-4db9-b0ba-a7d007dc9557)这几项怎么填写？

**Comment by jiang111** [comment]
> 注册链接: https://burn.hair/register?aff=LjKf
> 
> 对方的api文档如下:
> 
> https://github.com/BurnHair/issues/blob/master/doc.md

看了一下，他本身也是符合chatgpt API规范的，直接把key和域名填进去就可以用了

**Comment by Jonnyan404** [comment]
> > 注册链接: https://burn.hair/register?aff=LjKf
> > 对方的api文档如下:
> > https://github.com/BurnHair/issues/blob/master/doc.md
> 
> 看了一下，他本身也是符合chatgpt API规范的，直接把key和域名填进去就可以用了

报错,获取模型失败

**Comment by jiang111** [comment]
> > > 注册链接: https://burn.hair/register?aff=LjKf
> > > 对方的api文档如下:
> > > https://github.com/BurnHair/issues/blob/master/doc.md
> > 
> > 
> > 看了一下，他本身也是符合chatgpt API规范的，直接把key和域名填进去就可以用了
> 
> 报错,获取模型失败

你在 API Server 填的内容是什么

**Comment by Jonnyan404** [comment]
> > > > 注册链接: https://burn.hair/register?aff=LjKf
> > > > 对方的api文档如下:
> > > > https://github.com/BurnHair/issues/blob/master/doc.md
> > > 
> > > 
> > > 看了一下，他本身也是符合chatgpt API规范的，直接把key和域名填进去就可以用了
> > 
> > 
> > 报错,获取模型失败
> 
> 你在 API Server 填的内容是什么

https://burn.hair

**Comment by jiang111** [comment]
> > > > > 注册链接: https://burn.hair/register?aff=LjKf
> > > > > 对方的api文档如下:
> > > > > https://github.com/BurnHair/issues/blob/master/doc.md
> > > > 
> > > > 
> > > > 看了一下，他本身也是符合chatgpt API规范的，直接把key和域名填进去就可以用了
> > > 
> > > 
> > > 报错,获取模型失败
> > 
> > 
> > 你在 API Server 填的内容是什么
> 
> https://burn.hair

有没有选中这个地址，然后再点验证

**Comment by Jonnyan404** [comment]
> > > > > > 注册链接: https://burn.hair/register?aff=LjKf
> > > > > > 对方的api文档如下:
> > > > > > https://github.com/BurnHair/issues/blob/master/doc.md
> > > > > 
> > > > > 
> > > > > 看了一下，他本身也是符合chatgpt API规范的，直接把key和域名填进去就可以用了
> > > > 
> > > > 
> > > > 报错,获取模型失败
> > > 
> > > 
> > > 你在 API Server 填的内容是什么
> > 
> > 
> > https://burn.hair
> 
> 有没有选中这个地址，然后再点验证

稍等  我给你截图

**Comment by Jonnyan404** [comment]
> > > > > > 注册链接: https://burn.hair/register?aff=LjKf
> > > > > > 对方的api文档如下:
> > > > > > https://github.com/BurnHair/issues/blob/master/doc.md
> > > > > 
> > > > > 
> > > > > 看了一下，他本身也是符合chatgpt API规范的，直接把key和域名填进去就可以用了
> > > > 
> > > > 
> > > > 报错,获取模型失败
> > > 
> > > 
> > > 你在 API Server 填的内容是什么
> > 
> > 
> > https://burn.hair
> 
> 有没有选中这个地址，然后再点验证

![image](https://github.com/ChatBot-All/chatbot-app/assets/20352705/2bf1bc13-bcfd-427f-8a8c-f9ba4a17b375)

**Comment by jiang111** [comment]
> > > > > > > 注册链接: https://burn.hair/register?aff=LjKf
> > > > > > > 对方的api文档如下:
> > > > > > > https://github.com/BurnHair/issues/blob/master/doc.md
> > > > > > 
> > > > > > 
> > > > > > 看了一下，他本身也是符合chatgpt API规范的，直接把key和域名填进去就可以用了
> > > > > 
> > > > > 
> > > > > 报错,获取模型失败
> > > > 
> > > > 
> > > > 你在 API Server 填的内容是什么
> > > 
> > > 
> > > https://burn.hair
> > 
> > 
> > 有没有选中这个地址，然后再点验证
> 
> ![image](https://private-user-images.githubusercontent.com/20352705/326335290-2bf1bc13-bcfd-427f-8a8c-f9ba4a17b375.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjgzOTQsIm5iZiI6MTcxNDM2ODA5NCwicGF0aCI6Ii8yMDM1MjcwNS8zMjYzMzUyOTAtMmJmMWJjMTMtYmNmZC00MjdmLThhOGMtZjliYTRhMTdiMzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA1MjEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMTJjYzI0ZTBlMmM1ODQ1ODFhZjcwNDRlOWJiNWRjYzkwNmQzYjU5Yjk4OWQ3OGZkMmQ1MDE4ZTg4MGU0MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hxtO1ioZeN40Y6KH6Cz8gNnu5ZFaJpJY4JGzFXcK_5Q)

方便的话，临时生成一个API key,然后邮件发我 ,我调试一下 newtab12138#gmail.com (#-> @)

**Comment by Jonnyan404** [comment]
> > > > > > > > 注册链接: https://burn.hair/register?aff=LjKf
> > > > > > > > 对方的api文档如下:
> > > > > > > > https://github.com/BurnHair/issues/blob/master/doc.md
> > > > > > > 
> > > > > > > 
> > > > > > > 看了一下，他本身也是符合chatgpt API规范的，直接把key和域名填进去就可以用了
> > > > > > 
> > > > > > 
> > > > > > 报错,获取模型失败
> > > > > 
> > > > > 
> > > > > 你在 API Server 填的内容是什么
> > > > 
> > > > 
> > > > https://burn.hair
> > > 
> > > 
> > > 有没有选中这个地址，然后再点验证
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/20352705/326335290-2bf1bc13-bcfd-427f-8a8c-f9ba4a17b375.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjgzOTQsIm5iZiI6MTcxNDM2ODA5NCwicGF0aCI6Ii8yMDM1MjcwNS8zMjYzMzUyOTAtMmJmMWJjMTMtYmNmZC00MjdmLThhOGMtZjliYTRhMTdiMzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA1MjEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMTJjYzI0ZTBlMmM1ODQ1ODFhZjcwNDRlOWJiNWRjYzkwNmQzYjU5Yjk4OWQ3OGZkMmQ1MDE4ZTg4MGU0MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hxtO1ioZeN40Y6KH6Cz8gNnu5ZFaJpJY4JGzFXcK_5Q)
> 
> 方便的话，临时生成一个API key,然后邮件发我 ,我调试一下 newtab12138#gmail.com (#-> @)

已发送

**Comment by jiang111** [comment]
> ![image](https://private-user-images.githubusercontent.com/168355390/326329806-551f4f37-2153-4db9-b0ba-a7d007dc9557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjg5NzEsIm5iZiI6MTcxNDM2ODY3MSwicGF0aCI6Ii8xNjgzNTUzOTAvMzI2MzI5ODA2LTU1MWY0ZjM3LTIxNTMtNGRiOS1iMGJhLWE3ZDAwN2RjOTU1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQwNTMxMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmFmN2FkYTViYTJmZWZhYWEyODk1ZWRkNGIzZWVmOWNiNDkwZjYxYjViMmY0NTRiY2Y1NDY2MjRjMDYyMjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y0paVwdb4ht7E-94RzI1_PxA2k7eq-8DaV12vqdoHpY)这几项怎么填写？

填入你从OPEN AI官方或者第三方获取到的API key, 如果是第三方，还需要填写你对应的API Server

**Comment by jiang111** [comment]
部分三方API接口不规范，导致无法解析成功，已兼容
