### ISSUE TITLE
New API的key提示"Bad state:No element"

### ISSUE THREAD

**Issue by hscmcc1** [ChatBot-All/chatbot-app#9]
同样的key在别的平台，如Qchatbot以及网页部署都可以正常使用，在该项目中使用会报错:
"Bad state:No element"

**Comment by jiang111** [comment]
添加一张报错的截图看一下，key 可以打码

**Comment by hscmcc1** [comment]
![mmexport1715226867324.png](https://github.com/ChatBot-All/chatbot-app/assets/21263765/101b82a3-f8b8-4c98-9eed-02e59204bd7a)

**Comment by jiang111** [comment]
android端吗，app 版本是多少

**Comment by hscmcc1** [comment]
> android端吗，app 版本是多少

安卓端，上一个版本1.0.2有这个问题，升级到最新的1.0.3，仍然有问题。

**Comment by hscmcc1** [comment]
另外，还有一个渠道的apikey，验证支持的模型时，一直没有返回，也没有报错，apikey确定也是可用的，兼容openai，如有需要，可以提供apikey用于调试。

**Comment by jiang111** [comment]
邮件发我调试一下看看 newtab12138#gmail.com  # => @  API Key 和 API Server

**Comment by hscmcc1** [comment]
邮件已发

**Comment by jiang111** [comment]
没收到，注意一下 邮箱格式 把 # 换成 @
